export enum RepetitionType {
  HEDBOMADAIRE = 'HEDBOMADAIRE',

  JOURNALIER = 'JOURNALIER',

  MENSUEL = 'MENSUEL',

  BIMENSUEL = 'BIMENSUEL',

  TRIMESTRIEL = 'TRIMESTRIEL',

  SEMESTRIEL = 'SEMESTRIEL',

  ANNUEL = 'ANNUEL',
}
